Repository weweswap/app-page, pull requests merged in 2024-09, with the labels that each got.

#77 Update pools based on figma
  public/img/icons/Infinity.svg
  src/components/ui/Merge/MergeHome.tsx
  src/components/ui/Migrate/MigrateHome.tsx
  src/components/ui/Migrate/index.tsx
  src/components/ui/Pool/ActivePools.tsx
  src/components/ui/Pool/MyPools.tsx
  src/components/ui/Pool/PoolBox.tsx
  src/components/ui/Pool/PoolHome.tsx
  src/components/ui/Pool/dummy.ts
  src/components/ui/Swap/SwapHome.tsx
  src/pages/_app.tsx
Labels: Front-end

#79 Updated redeem modals
  package-lock.json
  src/components/common/FailTXModal.tsx
  src/components/ui/Merge/MergeCompleteModal.tsx
  src/components/ui/Merge/MergeOperation.tsx
  src/components/ui/Merge/RedeemCompleteModal.tsx
  src/components/ui/Merge/RedeemOperation.tsx
  src/components/ui/Swap/Swap.tsx
  src/hooks/useMerge.ts
  yarn.lock
Labels: enhancement, Front-end

#86 Update virtualBalance
  src/components/ui/Merge/MergeHome.tsx
  src/components/ui/Merge/MergeOperation.tsx
  src/components/ui/Merge/RedeemOperation.tsx
  src/components/ui/Redeem/RedeemHome.tsx
Labels: enhancement

#87 fix migrate icons
  public/img/tokens/uniswap-migrate.png
  src/components/ui/Migrate/MigrateDetail.tsx
  src/components/ui/Migrate/MigrateHome.tsx
Labels: bug

#88 Fix/pools
  public/img/icons/pending.svg
  src/components/ui/Pool/ActivePools.tsx
  src/components/ui/Pool/ClaimFeesModal.tsx
  src/components/ui/Pool/ClaimSuccessModal.tsx
  src/components/ui/Pool/Liquidity.tsx
  src/components/ui/Pool/LiquidityDetails.tsx
  src/components/ui/Pool/PoolHome.tsx
  src/components/ui/Pool/dummy.ts
Labels: enhancement

#91 Populate with real info positions list
  src/api/price.ts
  src/components/ui/Pool/Liquidity.tsx
  src/hooks/usePool.ts
  src/hooks/useWewePositions.ts
Labels: enhancement, Front-end

#92 Update wewe price provider
  src/api/price.ts
  src/components/ui/Merge/MergeHome.tsx
  src/components/ui/Merge/MergeOperation.tsx
  src/components/ui/Merge/RedeemOperation.tsx
  src/components/ui/Migrate/MigrateCompleteModal.tsx
  src/components/ui/Migrate/MigrateDetail.tsx
  src/components/ui/Redeem/RedeemHome.tsx
  src/constants/addresses.ts
  src/hooks/useMerge.ts
  src/lib/abis/CommonPool.ts
  src/services/index.ts
  src/services/price.ts
Labels: enhancement

#90 List pools + calculate TLV
  src/components/ui/Pool/ActivePools.tsx
  src/components/ui/Pool/Liquidity.tsx
  src/components/ui/Pool/PoolHome.tsx
  src/constants/addresses.ts
  src/hooks/usePool.ts
  src/hooks/useWewePositions.ts
  src/lib/abis/ArrakisFactory.ts
  src/lib/abis/ArrakisHelper.ts
  src/lib/abis/ArrakisResolver.ts
  src/lib/abis/ArrakisVault.ts
  src/lib/abis/UniswapPool.ts
  src/services/price.ts
  yarn.lock
Labels: question

#99 Added FE of deposit section along with its modals
  package-lock.json
  public/img/icons/swapwewe.svg
  src/components/ui/Pool/DepositSuccessModal.tsx
  src/components/ui/Pool/Liquidity.tsx
  src/components/ui/Pool/PoolDeposit.tsx
  src/components/ui/Pool/PoolDepositModal.tsx
  src/components/ui/Pool/WithdrawModal.tsx
  src/components/ui/Pool/WithdrawSuccessModal.tsx
  src/components/ui/Pool/index.tsx
  src/lib/config.ts
  yarn.lock
Labels: enhancement, Front-end

#110 Enable swap on menu
  src/components/ui/NavBar/links.ts
Labels: enhancement, Front-end

#111 Withdrawal bug fix
  src/components/ui/Pool/ApproveTokens.tsx
  src/components/ui/Pool/PoolDeposit.tsx
Labels: bug, enhancement, Front-end

#109 fetch vault apr from backend
  src/hooks/usePool.ts
Labels: enhancement, Front-end, Back-end

#117 Slippage update
  package.json
  src/components/ui/Migrate/MigrateDetail.tsx
  src/constants/addresses.ts
  src/hooks/useMigrate.ts
  yarn.lock
Labels: enhancement, Back-end

#121 add daily fees in usd
  src/components/ui/Pool/PoolDeposit.tsx
  src/hooks/usePool.ts
Labels: enhancement, Front-end

#120 add user balances in deposit
  src/components/ui/Pool/PoolDeposit.tsx
Labels: enhancement, Front-end, Back-end

#123 Add: volume added to pool details
  src/hooks/usePool.ts
  yarn.lock
Labels: enhancement, Front-end

#125 New deploy with FeeManager fix
  src/constants/addresses.ts
Labels: bug, enhancement, Back-end

#126 Add 'Migrate' and 'Pools' in the menu
  src/components/ui/NavBar/links.ts
Labels: enhancement, Front-end

#137 Add more info in withdrawal success modal
  src/components/ui/Migrate/MigrateCompleteModal.tsx
  src/components/ui/Migrate/MigrateDetail.tsx
Labels: bug, enhancement, Front-end
