Repository weweswap/app-page, pull requests merged in 2024-10, with the labels that each got.

#152 feat: implement queries for bro merge
  src/components/ui/Merge/Bro/BBroMergeForm.tsx
  src/components/ui/Merge/Bro/BroMergeForm.tsx
  src/components/ui/Merge/Bro/MergeCompleteModal.tsx
  src/components/ui/NavBar/NavLink.tsx
  src/hooks/useEater.ts
  src/pages/merge/bro/index.tsx
  src/pages/merge/index.tsx
Labels: enhancement, Front-end

#156 improve pool loading
  src/hooks/usePool.ts
  src/hooks/useWewePositions.ts
Labels: enhancement, Front-end

#158 refactor: improve performance of useGetPrices hook
  src/hooks/useGetPrices.ts
Labels: enhancement, Front-end

#163 fix: bro merge decimal number issue
  src/components/ui/Merge/Bro/BBroMergeForm.tsx
  src/components/ui/Merge/Bro/BroMergeForm.tsx
  src/components/ui/Merge/Bro/MergeProcessingModal.tsx
Labels: bug, Front-end

#166 Update MergeHome.tsx
  src/components/ui/Merge/Vult/MergeHome.tsx
Labels: bug, Front-end

#172 updated contract address of feeManager
  package-lock.json
  src/constants/addresses.ts
  yarn.lock
Labels: bug, Front-end

#173 fixing package manager issue
  package-lock.json
  yarn.lock
Labels: bug, enhancement, Front-end

#176 feature: add chaos reward to pool
  src/components/ui/Pool/ClaimFeesModal.tsx
  src/components/ui/Pool/ClaimSuccessModal.tsx
  src/components/ui/Pool/MyShares.tsx
  src/components/ui/Pool/PoolDeposit.tsx
  src/components/ui/Pool/PoolPriceChart.tsx
  src/components/ui/Pool/PoolTvlChart.tsx
  src/components/ui/Pool/PoolVolumeChart.tsx
  src/components/ui/Pool/WithdrawSuccessModal.tsx
  src/components/ui/Pool/index.tsx
  src/hooks/useWewePositions.ts
  src/lib/abis/FeeManager.ts
  src/utils/index.ts
Labels: enhancement, Front-end

#180 Added FE of Meme merge
  public/img/tokens/FOMO.webp
  public/img/tokens/goodle.svg
  src/components/common/LoadingScreen.tsx
  src/components/ui/Background/index.tsx
  src/components/ui/Merge/Bro/BBroMergeForm.tsx
  src/components/ui/Merge/Bro/BroMergeForm.tsx
  src/components/ui/Merge/Bro/MergeProcessingModal.tsx
  src/components/ui/Merge/Memes/ChaosRewardCard.tsx
  src/components/ui/Merge/Memes/ClaimCompleteModal.tsx
  src/components/ui/Merge/Memes/ClaimProcessingModal.tsx
  src/components/ui/Merge/Memes/MemeClaimForm.tsx
  src/components/ui/Merge/Memes/MemeMergeForm.tsx
  src/components/ui/Merge/Memes/MergeCompleteModal.tsx
  src/components/ui/Merge/Memes/MergePriceChart.tsx
  src/components/ui/Merge/Memes/MergeProcessingModal.tsx
  src/constants/mergeConfigs.ts
  src/hooks/useMemeEater.ts
  src/lib/abis/MemeEaterABI.ts
  src/pages/_app.tsx
  src/pages/merge/[slug]/index.tsx
  src/pages/merge/index.tsx
Labels: enhancement, Front-end
